import type { Dict } from './types'

export const en: Dict = {
  meta: {
    title: 'Daniel Liberto · UI/UX Designer & Front-end Engineer',
    description:
      'Daniel Liberto de Almeida designs interfaces and writes the code that ships them. Fintech products, motion and WebGL with React, TypeScript, Three.js and GSAP.',
  },
  nav: {
    work: 'Work',
    services: 'Services',
    about: 'Journey',
    contact: 'Contact',
    menu: 'Menu',
    close: 'Close',
    sound: 'Sound',
    skip: 'Skip to content',
    back: 'Back',
    home: 'Home',
  },
  preloader: { file: 'Portfolio · Daniel Liberto', compiling: 'Compiling design', ready: 'Ready' },
  hero: {
    edition: 'Portfolio · 2026 Edition',
    role: 'UI/UX Designer',
    roleB: '& Front-end Engineer',
    intro: 'I design interfaces and write the code that ships them. Fintech products, motion and WebGL.',
    available: 'Open to new challenges',
    location: 'Assis, SP · Brazil',
    scroll: 'Scroll to see the layers',
    layers: ['Background · room.jpg', 'Text · Daniel', 'Cut-out · Daniel (Vision)', 'Text + UI · Liberto'],
  },
  anatomy: {
    label: 'Anatomy',
    title: 'Anatomy of a',
    titleB: 'senior designer',
    file: 'daniel.jpg',
    zoom: 'Zoom',
    items: [
      {
        key: 'brow',
        title: 'Code review eyebrow',
        text: 'Raises **itself** whenever it spots a **15px** padding on an 8pt grid.',
      },
      {
        key: 'lens',
        title: 'Calibrated lenses',
        text: 'Spot a **1px** misalignment from **two meters** away. **800%** zoom included.',
      },
      {
        key: 'brain',
        title: 'Bilingual brain',
        text: 'Thinks in **Figma** and dreams in **TypeScript**. Fluent in both **designer** and **developer**.',
      },
      {
        key: 'beard',
        title: 'Build 31.0',
        text: '31 years old, **stable** release, **zero breaking changes**. The full changelog is right above.',
      },
      {
        key: 'jacket',
        title: 'Dark mode by default',
        text: 'Factory setting, **cannot be turned off**. **AA** contrast guaranteed on any theme.',
      },
      {
        key: 'env',
        title: 'Dev environment',
        text: 'Assis, SP · GMT-3. **Remote**, working with teams in **any time zone**.',
      },
    ],
    outro: 'Specs subject to coffee.',
  },
  manifesto: {
    label: 'Manifesto',
    text: 'I design [interfaces]{serif} that feel obvious and write the [code]{code} that takes them [live.]{mark} Nothing gets lost between [Figma]{chip} and the [product.]{pill}',
    cursor: 'Daniel',
    stats: [
      { value: 3, suffix: '', label: 'Fintech products designed and built' },
      { value: 1800, suffix: '+', label: 'Commits shipped to production' },
      { value: 4, suffix: '', label: 'Languages shipped (PT · EN · ES · FR)' },
      { value: 2, suffix: '', label: 'Sides of the product: design and code' },
    ],
  },
  process: {
    label: 'Process',
    title: 'From scribble',
    titleB: 'to product',
    stages: [
      {
        name: 'Scribble',
        text: 'Every interface starts ugly. Pen, paper and one question: what does the person need to see first?',
      },
      {
        name: 'Interface',
        text: 'In Figma the scribble gets a grid, tokens and components. Every spacing has a reason.',
      },
      {
        name: 'Code',
        text: 'The same component, now in React and TypeScript. Design tokens become code variables, one to one.',
      },
      {
        name: 'Product',
        text: 'Live, with real data, motion and states. This is where design gets truly tested.',
      },
    ],
    card: {
      title: 'Wallet',
      balance: 'Available balance',
      amount: '48,320.90',
      currency: 'USDT',
      delta: '+4.2% today',
      send: 'Send',
      receive: 'Receive',
      recent: 'Recent',
      tx: [
        { name: 'Payment received', value: '+1,200.00' },
        { name: 'BRL conversion', value: '−860.40' },
      ],
      notes: ['big balance!', 'green = up', 'main action', '7-day chart?'],
      notif: 'Payment received',
      notifValue: '$1,200.00 · now',
    },
    design: { colors: 'Colors', type: 'Typography', spacing: 'Spacing', component: 'Component', autoLayout: 'Auto layout' },
    code: { file: 'WalletCard.tsx', compiled: 'Compiled in 212ms' },
    product: { live: 'Live', hint: 'Hover the card' },
  },
  work: {
    label: 'Work',
    title: 'Selected',
    titleB: 'work',
    intro:
      'Three products, one obsession: making money move beautifully. Scroll sideways through the cases and open any of them for the full story.',
    view: 'View case',
    live: 'Live site',
    moreTitle: 'And much more',
    moreText: '30+ repositories in production: admin panels, white-labels, academies, marketplaces and native apps.',
    moreCta: 'See GitHub',
    archive: 'Archive',
    private: 'Private',
    drag: 'Drag',
  },
  case: {
    overview: 'Overview',
    challenge: 'Challenge',
    solution: 'Approach',
    highlights: 'Highlights',
    gallery: 'Selected screens',
    next: 'Next case',
    back: 'All work',
    visit: 'Visit live site',
    scroll: 'Scroll',
    role: 'Role',
    year: 'Period',
    platforms: 'Platforms',
    stack: 'Stack',
    metricsNote: '*Public figures shared by the company.',
    holdNext: 'Keep scrolling to open',
  },
  projects: {
    tcr: {
      tagline: 'Digital dollar at wholesale speed',
      category: 'Fintech · OTC Desk · USDT',
      role: 'Product Design · Front-end · Mobile',
      summary:
        'An OTC desk for buying and selling USDT in volume, with a WebGL particle wolf, real-time quotes and native apps.',
      overview:
        'TCR is a digital-dollar (USDT) wholesale desk for companies and resellers: locked quotes, verifiable settlement via Pix and human support. I designed and built its front-end surfaces: the trading platform, the OTC desk, the white-label, the native apps and the landing page.',
      challenge:
        'Wholesale crypto is all about trust. Users move large amounts and need to know, at every step, the price, the status and the proof that they received what they bought. The brand also needed to feel bold and premium against generic exchanges.',
      solution:
        'A dark, editorial system with a single orange signal for action and status. Quotes, steps and receipts are explicit and auditable. On the landing page, a Three.js particle wolf gives the brand a living identity, while the app stays fast and data-dense with TanStack Query and Recharts.',
      highlights: [
        'WebGL particle wolf hero built with React Three Fiber',
        'Trading platform with real-time quotes and order flows',
        'Dedicated OTC desk, white-label and admin surfaces',
        'Native iOS/Android app with Expo & React Native',
      ],
      platforms: ['Web app', 'OTC desk', 'Landing', 'iOS / Android', 'White-label'],
      metrics: [
        { value: 'R$3B+', label: 'Traded on the desk*' },
        { value: '3,000+', label: 'Companies served*' },
        { value: '570+', label: 'My commits across TCR repos' },
      ],
      captions: ['OTC desk narrative', 'API section', '3-step flow', 'Product overview'],
    },
    vcx: {
      tagline: 'Global payments. Instant settlement.',
      category: 'Fintech · Payments · Stablecoins',
      role: 'UI/UX Design · Front-end',
      summary:
        'Payment infrastructure that connects Brazilian companies to the world: FX, Pix and stablecoin settlement in under 60 seconds.',
      overview:
        'VCX (Vision Cash Exchange) lets companies deposit, withdraw and convert between fiat and crypto (BRL, USD, EUR, BTC, ETH, USDT, SOL, BNB and TRX) with real-time quotes. I worked on the interface of the platform and its marketing site.',
      challenge:
        'Cross-border payments are opaque by nature: spreads, hidden fees and days of waiting. The product had to make a complex multi-currency engine feel as simple as sending a Pix, in three languages and two themes.',
      solution:
        'A neon-lime accent on deep black to signal speed, a clear three-step mental model (instruct, convert, settle) and a calm, modular dashboard for wallets, conversions and history, built with React, shadcn/ui and Recharts, fully localized in PT/EN/ES with light and dark themes.',
      highlights: [
        'Multi-currency wallet: deposit, withdraw, convert, transfer',
        'Real-time conversion between fiat and crypto',
        'PT / EN / ES localization with light and dark themes',
        'Marketing site with a global, B2B narrative',
      ],
      platforms: ['Web app', 'Marketing site', 'Admin'],
      metrics: [
        { value: '<60s', label: 'Average settlement*' },
        { value: '9', label: 'Currencies supported' },
        { value: '3', label: 'Languages · 2 themes' },
      ],
      captions: ['Sign-in experience', 'Services and metrics', 'How it works', 'Built for global companies'],
    },
    hubib: {
      tagline: 'The network of money',
      category: 'Crypto ecosystem · Wallet · Cards',
      role: 'Product Design · Front-end · Creative Dev',
      summary:
        'A global crypto ecosystem (wallet, cards, academy and marketplace) with a cinematic landing page powered by WebGL and GSAP.',
      overview:
        'Hubib is a digital financial ecosystem where users learn (Academy), move money (Wallet and Cards) and consume opportunities (Marketplace). I am the top contributor to the core app and built the new landing page, the brand’s cinematic front door.',
      challenge:
        'Explain a whole ecosystem, not just a wallet, in one scroll, for a global audience, without losing the premium feel. And keep it fast on mobile.',
      solution:
        'A storytelling landing page: a 20,500-particle logo that dissolves on scroll, glass-like shards, curtain transitions with GSAP ScrollTrigger and a completely re-architected mobile version. Inside the app, a consistent design language across wallet, cards, rewards and marketplace.',
      highlights: [
        '20,500-particle WebGL logo that dissolves on scroll',
        'GSAP curtain and squeeze transitions, Lenis smooth scroll',
        'Mobile experience rebuilt from scratch',
        'Fully translated: PT · EN · ES · FR',
      ],
      platforms: ['Landing', 'Web app', 'iOS / Android', 'Academy', 'Marketplace'],
      metrics: [
        { value: '20.5k', label: 'Particles in the hero logo' },
        { value: '640+', label: 'My commits on the core app' },
        { value: '4', label: 'Languages shipped' },
      ],
      captions: ['Bento of the ecosystem', 'Choose your card', 'Imperial card', 'Step-by-step onboarding', 'Brand moment'],
    },
  },
  archive: [
    { name: 'Hubib App', kind: 'Web app', year: '2025' },
    { name: 'TCR Mobile', kind: 'iOS / Android', year: '2025' },
    { name: 'Hubib Academy', kind: 'Platform', year: '2026' },
    { name: 'TCR White-label', kind: 'SaaS', year: '2025' },
    { name: 'Sky Markets', kind: 'Prediction market', year: '2026' },
    { name: 'Hubib Admin', kind: 'Back-office', year: '2025' },
  ],
  services: {
    label: 'Services',
    title: 'What I',
    titleB: 'deliver',
    intro: 'Five fronts, the same care. I can join at the very start of an idea, in the middle of the code or at the last detail of motion.',
    deliverables: 'Deliverables',
    items: [
      {
        title: 'Product Design',
        text: 'From a fuzzy problem to a clear flow. Research, journeys, wireframes and prototypes that de-risk the product before the first line of code.',
        deliverables: ['Research and journeys', 'Wireframes and flows', 'Clickable prototypes', 'Usability testing'],
      },
      {
        title: 'UI & Design Systems',
        text: 'Visual languages that scale: tokens, components and Figma documentation that map one to one with the code.',
        deliverables: ['High-fidelity interfaces', 'Design tokens', 'Component libraries', 'Illustration in Illustrator'],
      },
      {
        title: 'Front-end Engineering',
        text: 'Production React and TypeScript: data-dense dashboards, i18n, accessibility and a performance budget taken seriously.',
        deliverables: ['React · TypeScript · Vite', 'Tailwind · shadcn/ui', 'i18n and accessibility', 'Performance'],
      },
      {
        title: 'Motion & Creative Dev',
        text: 'The layer people remember. GSAP choreography, Three.js scenes and shaders, always in service of the story.',
        deliverables: ['GSAP · ScrollTrigger', 'Three.js · WebGL · GLSL', 'Immersive landing pages', 'Micro-interactions'],
      },
      {
        title: 'Apps & Back-end',
        text: 'The same care outside the browser: iOS and Android apps with React Native and Expo, and Node.js for APIs and integrations.',
        deliverables: ['React Native', 'Expo', 'Node.js', 'Integrations and APIs'],
      },
    ],
  },
  toolbox: {
    label: 'Tools',
    title: 'Toolbox',
    hint: 'Scroll and I will type it for you.',
    space: 'space for your project',
    groups: [
      { title: 'Design', items: ['Figma', 'Illustrator', 'Design Systems', 'Prototypes', 'UX Research', 'Accessibility'] },
      { title: 'Front-end', items: ['React', 'TypeScript', 'Vite', 'Tailwind', 'shadcn/ui', 'TanStack', 'Zod', 'i18next'] },
      { title: 'Motion & 3D', items: ['GSAP', 'Three.js', 'R3F', 'GLSL', 'Lenis', 'Framer Motion'] },
      { title: 'Mobile & back-end', items: ['React Native', 'Expo', 'Node.js', 'Git', 'Java', 'Python'] },
    ],

  },
  changelog: {
    label: 'Journey',
    title: 'Release notes',
    version: 'Daniel 31.0',
    intro: 'My path, documented the way I document software: by releases.',
    head: 'You are here',
    kinds: { added: 'Added', improved: 'Improved', fixed: 'Fixed', merged: 'Merged' },
    entries: [
      {
        version: 'v19.0',
        date: '2019',
        branch: 'unopar',
        kind: 'branch',
        title: 'Systems Analysis and Development',
        place: 'Unopar · Assis (SP)',
        notes: [
          { kind: 'added', text: 'Logic, databases and software engineering' },
          { kind: 'added', text: 'Complete Java course' },
          { kind: 'added', text: '190h of UX/UI, HTML, CSS, JavaScript and React (Origamid)' },
        ],
      },
      {
        version: 'v21.0',
        date: '2021',
        branch: 'unopar',
        kind: 'merge',
        title: 'Graduated',
        place: 'Merged unopar into main',
        notes: [
          { kind: 'merged', text: 'Degree completed' },
          { kind: 'improved', text: 'A solid base for bringing design and code together' },
        ],
      },
      {
        version: 'v24.0',
        date: '2024',
        branch: 'grupo-nexus',
        kind: 'branch',
        title: 'UI/UX Designer & Front-end Engineer',
        place: 'Grupo Nexus · since 2024',
        notes: [
          { kind: 'added', text: 'A suite of finance and crypto products: TCR, VCX, Hubib and Sky Markets' },
          { kind: 'improved', text: 'Web apps, landing pages, dashboards and React Native apps' },
        ],
      },
      {
        version: 'v24.1',
        date: '2024',
        branch: 'tcr-finance',
        kind: 'branch',
        title: 'Product Designer & Front-end Engineer',
        place: 'TCR Finance · since 2024',
        notes: [
          { kind: 'added', text: 'Platform, OTC desk, white-label and iOS/Android app' },
          { kind: 'added', text: 'WebGL particle wolf hero' },
        ],
      },
      {
        version: 'v25.0',
        date: '2025',
        branch: 'hubib',
        kind: 'branch',
        title: 'Product Designer & Creative Front-end',
        place: 'Hubib · since 2025',
        notes: [
          { kind: 'added', text: 'Top contributor to the core app' },
          { kind: 'added', text: 'Cinematic landing page with WebGL, GSAP and Lenis' },
        ],
      },
      {
        version: 'v31.0',
        date: '2026',
        branch: 'main',
        kind: 'head',
        title: 'Daniel 31.0',
        place: 'Current release · stable',
        notes: [
          { kind: 'added', text: 'This portfolio, from the first scribble to the last easing' },
          { kind: 'improved', text: 'Design systems that go from Figma to code losslessly' },
          { kind: 'fixed', text: 'No 15px padding survived' },
        ],
      },
    ],
    languagesTitle: 'Languages',
    languages: 'Portuguese (native) · English',
    educationTitle: 'Education',
    education: [
      { title: 'Systems Analysis and Development', place: 'Unopar, Assis (SP)', detail: '2019 to 2021' },
      { title: 'UX/UI Design · HTML & CSS · JavaScript · React', place: 'Origamid', detail: '190h of intensive courses' },
      { title: 'Complete Java', place: 'Unopar', detail: 'Complete course' },
      { title: 'Python', place: 'Udemy', detail: 'Back-end fundamentals' },
    ],
  },
  contact: {
    label: 'Contact',
    titleA: 'Got a',
    scribble: 'scribble',
    titleB: 'lying around?',
    text: 'I turn it into a product. Open to full-time roles and selected freelance projects, remote, anywhere in the world.',
    copy: 'Copy email',
    copied: 'Copied to clipboard',
    whatsapp: 'Message on WhatsApp',
    response: 'I reply within 24h',
    socials: 'Socials',
    more: 'Keep scrolling. There is one more thing.',
  },
  finale: {
    joined: 'Daniel joined the file',
    file: 'Portfolio · Daniel Liberto',
    pages: ['Website', 'Design system', 'Scribbles'],
    layers: 'Layers',
    design: 'Design',
    prototype: 'Prototype',
    you: 'You',
    comment: 'Everything you just saw was designed here and built there. Like it? Let’s make yours.',
    reply: 'Reply by email',
    present: 'Present',
    hint: 'Drag to pan · Ctrl + scroll to zoom',
    hintTouch: 'Drag to pan · pinch to zoom',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit all',
    frames: [
      { id: 'hero', name: 'Hero' },
      { id: 'manifesto', name: 'Manifesto' },
      { id: 'process', name: 'Process' },
      { id: 'work', name: 'Work' },
      { id: 'services', name: 'Services' },
      { id: 'toolbox', name: 'Toolbox' },
      { id: 'changelog', name: 'Release notes' },
      { id: 'contact', name: 'Contact' },
    ],
    tokensTitle: 'Colors',
    typeTitle: 'Typography',
    componentsTitle: 'Components',
    credits: 'Credits',
    creditsText: 'Designed in Figma and built with React, TypeScript, Three.js, GSAP, Lenis and Matter.js.',
    sticky: 'note to self: hire Daniel',
  },
  postCredits: {
    label: 'Post-credits scene',
    credits: [
      { role: 'Directed by', name: 'Me' },
      { role: 'Written by', name: 'Also me' },
      { role: 'Product Design', name: 'Me again' },
      { role: 'Interface', name: 'Guess who? Me' },
      { role: 'Front-end', name: 'Still me' },
      { role: 'Motion & WebGL', name: 'Yep, me (again)' },
      { role: 'Visual effects', name: 'Three.js · GSAP' },
      { role: 'Smooth scroll', name: 'Lenis' },
      { role: 'Original score', name: 'Tone.js (generated in code)' },
      { role: 'Pixel review', name: "Daniel's glasses" },
      { role: 'Catering', name: 'Coffee. A lot of coffee.' },
      { role: 'Very special thanks', name: 'You, for making it all the way down here' },
    ],
    creditsTitle: 'Credits',
    disclaimer: 'No pixels were harmed in the making of this website.',
    presents: 'presents',
    presentsTitle: 'Post-credits',
    thanks: 'Thank you for watching until the very end, credits included. If this portfolio made you smile, imagine your product. Let’s talk.',
    end: 'Now it is really over.',
    top: 'Back to top',
  },
  footer: {
    built: 'Designed and built by Daniel Liberto.',
    rights: 'All rights reserved.',
    top: 'Back to top',
    local: 'Local time',
  },
  notFound: {
    title: 'Frame not found',
    text: 'This page was deleted from the file, or never existed.',
    cta: 'Back home',
  },
}
