import type { Dict } from './types'

export const pt: Dict = {
  meta: {
    title: 'Daniel Liberto · UI/UX Designer & Front-end Engineer',
    description:
      'Daniel Liberto de Almeida desenha interfaces e escreve o código que as coloca no ar. Produtos financeiros, motion e WebGL com React, TypeScript, Three.js e GSAP.',
  },
  nav: {
    work: 'Projetos',
    services: 'Serviços',
    about: 'Trajetória',
    contact: 'Contato',
    menu: 'Menu',
    close: 'Fechar',
    sound: 'Som',
    skip: 'Pular para o conteúdo',
    back: 'Voltar',
    home: 'Início',
  },
  preloader: { file: 'Portfólio · Daniel Liberto', compiling: 'Compilando design', ready: 'Pronto' },
  hero: {
    edition: 'Portfólio · Edição 2026',
    role: 'UI/UX Designer',
    roleB: '& Front-end Engineer',
    intro: 'Desenho interfaces e escrevo o código que as coloca no ar. Produtos financeiros, motion e WebGL.',
    available: 'Disponível para novos desafios',
    location: 'Assis, SP · Brasil',
    scroll: 'Role para ver as camadas',
    layers: ['Fundo · sala.jpg', 'Texto · Daniel', 'Recorte · Daniel (Vision)', 'Texto + UI · Liberto'],
  },
  anatomy: {
    label: 'Anatomia',
    title: 'Anatomia de um',
    titleB: 'designer sênior',
    file: 'daniel.jpg',
    zoom: 'Zoom',
    items: [
      {
        key: 'brow',
        title: 'Sobrancelha de code review',
        text: 'Sobe **sozinha** quando encontra um padding de **15px** num grid de 8.',
      },
      {
        key: 'lens',
        title: 'Lentes calibradas',
        text: 'Enxergam **1px** de desalinhamento a **dois metros** de distância. Zoom de **800%** incluso.',
      },
      {
        key: 'brain',
        title: 'Cérebro bilíngue',
        text: 'Pensa em **Figma** e sonha em **TypeScript**. Fluente em **designês** e em **devês**.',
      },
      {
        key: 'beard',
        title: 'Build 31.0',
        text: '31 anos, versão **estável**, **zero breaking changes**. O changelog completo está logo acima.',
      },
      {
        key: 'jacket',
        title: 'Dark mode de fábrica',
        text: 'Configuração de fábrica, **não dá para desativar**. Contraste **AA** garantido em qualquer tema.',
      },
      {
        key: 'env',
        title: 'Ambiente de desenvolvimento',
        text: 'Assis, SP · GMT-3. **Remoto**, trabalhando com times de **qualquer fuso**.',
      },
    ],
    outro: 'Especificações sujeitas a café.',
  },
  manifesto: {
    label: 'Manifesto',
    text: 'Eu desenho [interfaces]{serif} que parecem óbvias e escrevo o [código]{code} que as coloca [no ar.]{mark} Nada se perde entre o [Figma]{chip} e o [produto.]{pill}',
    cursor: 'Daniel',
    stats: [
      { value: 3, suffix: '', label: 'Produtos fintech desenhados e desenvolvidos' },
      { value: 1800, suffix: '+', label: 'Commits enviados para produção' },
      { value: 4, suffix: '', label: 'Idiomas entregues (PT · EN · ES · FR)' },
      { value: 2, suffix: '', label: 'Lados do produto: design e código' },
    ],
  },
  process: {
    label: 'Processo',
    title: 'Do rabisco',
    titleB: 'ao produto',
    stages: [
      {
        name: 'Rabisco',
        text: 'Toda interface começa feia. Papel, caneta e uma pergunta: o que a pessoa precisa ver primeiro?',
      },
      {
        name: 'Interface',
        text: 'No Figma, o rabisco ganha grid, tokens e componentes. Cada espaçamento tem um motivo.',
      },
      {
        name: 'Código',
        text: 'O mesmo componente, agora em React e TypeScript. Os tokens do design viram variáveis no código, um para um.',
      },
      {
        name: 'Produto',
        text: 'No ar, com dados reais, movimento e estados. É aqui que o design é testado de verdade.',
      },
    ],
    card: {
      title: 'Carteira',
      balance: 'Saldo disponível',
      amount: '48.320,90',
      currency: 'USDT',
      delta: '+4,2% hoje',
      send: 'Enviar',
      receive: 'Receber',
      recent: 'Recentes',
      tx: [
        { name: 'Pix recebido', value: '+1.200,00' },
        { name: 'Conversão BRL', value: '−860,40' },
      ],
      notes: ['saldo bem grande!', 'verde = subiu', 'ação principal', 'gráfico de 7 dias?'],
      notif: 'Pix recebido',
      notifValue: 'R$ 1.200,00 · agora',
    },
    design: { colors: 'Cores', type: 'Tipografia', spacing: 'Espaçamento', component: 'Componente', autoLayout: 'Auto layout' },
    code: { file: 'WalletCard.tsx', compiled: 'Compilado em 212ms' },
    product: { live: 'Ao vivo', hint: 'Passe o mouse no cartão' },
  },
  work: {
    label: 'Projetos',
    title: 'Projetos',
    titleB: 'selecionados',
    intro:
      'Três produtos, uma obsessão: fazer o dinheiro se mover com beleza. Role para o lado pelos cases e abra qualquer um para ver a história completa.',
    view: 'Ver case',
    live: 'Site no ar',
    moreTitle: 'E muito mais',
    moreText: '30+ repositórios em produção: admins, white-labels, academias, marketplaces e apps nativos.',
    moreCta: 'Ver GitHub',
    archive: 'Arquivo',
    private: 'Privado',
    drag: 'Arraste',
  },
  case: {
    overview: 'Visão geral',
    challenge: 'Desafio',
    solution: 'Abordagem',
    highlights: 'Destaques',
    gallery: 'Telas selecionadas',
    next: 'Próximo case',
    back: 'Todos os projetos',
    visit: 'Visitar site',
    scroll: 'Role',
    role: 'Função',
    year: 'Período',
    platforms: 'Plataformas',
    stack: 'Stack',
    metricsNote: '*Números públicos divulgados pela empresa.',
    holdNext: 'Continue rolando para abrir',
  },
  projects: {
    tcr: {
      tagline: 'Dólar digital na velocidade do atacado',
      category: 'Fintech · Mesa OTC · USDT',
      role: 'Product Design · Front-end · Mobile',
      summary:
        'Uma mesa OTC para comprar e vender USDT em volume, com um lobo de partículas em WebGL, cotações em tempo real e apps nativos.',
      overview:
        'A TCR é uma mesa de dólar digital (USDT) no atacado para empresas e revendedores: cotação travada, liquidação verificável via Pix e atendimento humano. Desenhei e desenvolvi suas superfícies de front-end: a plataforma, a mesa OTC, o white-label, os apps nativos e a landing page.',
      challenge:
        'Cripto no atacado é sobre confiança. O usuário movimenta valores altos e precisa saber, a cada etapa, o preço, o status e a prova de que recebeu o que comprou. A marca também precisava soar ousada e premium frente às exchanges genéricas.',
      solution:
        'Um sistema escuro e editorial com um único sinal laranja para ação e status. Cotações, etapas e comprovantes são explícitos e auditáveis. Na landing, um lobo de partículas em Three.js dá à marca uma identidade viva, enquanto o app segue rápido e denso em dados com TanStack Query e Recharts.',
      highlights: [
        'Hero com lobo de partículas em WebGL (React Three Fiber)',
        'Plataforma com cotações em tempo real e fluxo de ordens',
        'Mesa OTC dedicada, white-label e painel administrativo',
        'App nativo iOS/Android com Expo e React Native',
      ],
      platforms: ['Web app', 'Mesa OTC', 'Landing', 'iOS / Android', 'White-label'],
      metrics: [
        { value: 'R$3B+', label: 'Operados na mesa*' },
        { value: '3.000+', label: 'Empresas atendidas*' },
        { value: '570+', label: 'Meus commits nos repositórios TCR' },
      ],
      captions: ['Narrativa da mesa OTC', 'Seção de API', 'Fluxo em 3 passos', 'Visão do produto'],
    },
    vcx: {
      tagline: 'Pagamentos globais. Liquidação instantânea.',
      category: 'Fintech · Pagamentos · Stablecoins',
      role: 'UI/UX Design · Front-end',
      summary:
        'Infraestrutura de pagamentos que conecta empresas brasileiras ao mundo: câmbio, Pix e liquidação em stablecoins em menos de 60 segundos.',
      overview:
        'A VCX (Vision Cash Exchange) permite depositar, sacar e converter entre moedas fiat e cripto (BRL, USD, EUR, BTC, ETH, USDT, SOL, BNB e TRX) com cotações em tempo real. Trabalhei na interface da plataforma e do site institucional.',
      challenge:
        'Pagamentos internacionais são opacos por natureza: spreads, taxas escondidas e dias de espera. O produto precisava fazer um motor multimoeda complexo parecer tão simples quanto mandar um Pix, em três idiomas e dois temas.',
      solution:
        'Um acento verde-limão neon sobre preto profundo para sinalizar velocidade, um modelo mental claro em três passos (instruir, converter, liquidar) e um dashboard calmo e modular para carteiras, conversões e histórico, com React, shadcn/ui e Recharts, totalmente localizado em PT/EN/ES com temas claro e escuro.',
      highlights: [
        'Carteira multimoeda: depositar, sacar, converter, transferir',
        'Conversão em tempo real entre fiat e cripto',
        'Localização PT / EN / ES com temas claro e escuro',
        'Site institucional com narrativa global e B2B',
      ],
      platforms: ['Web app', 'Site institucional', 'Admin'],
      metrics: [
        { value: '<60s', label: 'Liquidação média*' },
        { value: '9', label: 'Moedas suportadas' },
        { value: '3', label: 'Idiomas · 2 temas' },
      ],
      captions: ['Experiência de login', 'Serviços e métricas', 'Como funciona', 'Feita para empresas globais'],
    },
    hubib: {
      tagline: 'A rede do dinheiro',
      category: 'Ecossistema cripto · Wallet · Cartões',
      role: 'Product Design · Front-end · Creative Dev',
      summary:
        'Um ecossistema cripto global (wallet, cartões, academy e marketplace) com uma landing cinematográfica movida a WebGL e GSAP.',
      overview:
        'A Hubib é um ecossistema financeiro digital onde o usuário aprende (Academy), movimenta dinheiro (Wallet e Cartões) e consome oportunidades (Marketplace). Sou o maior contribuidor do app principal e construí a nova landing page, a porta de entrada cinematográfica da marca.',
      challenge:
        'Explicar um ecossistema inteiro, não só uma wallet, em um único scroll, para um público global, sem perder o tom premium. E manter tudo rápido no mobile.',
      solution:
        'Uma landing narrativa: um logo de 20.500 partículas que se dissolve no scroll, estilhaços de vidro, transições de cortina com GSAP ScrollTrigger e uma versão mobile reconstruída do zero. Dentro do app, uma linguagem consistente entre wallet, cartões, recompensas e marketplace.',
      highlights: [
        'Logo em WebGL com 20.500 partículas que se dissolve no scroll',
        'Transições de cortina e squeeze com GSAP, scroll suave com Lenis',
        'Experiência mobile reconstruída do zero',
        'Totalmente traduzida: PT · EN · ES · FR',
      ],
      platforms: ['Landing', 'Web app', 'iOS / Android', 'Academy', 'Marketplace'],
      metrics: [
        { value: '20,5k', label: 'Partículas no logo do hero' },
        { value: '640+', label: 'Meus commits no app principal' },
        { value: '4', label: 'Idiomas entregues' },
      ],
      captions: ['Bento do ecossistema', 'Escolha seu cartão', 'Cartão Imperial', 'Onboarding passo a passo', 'Momento de marca'],
    },
  },
  archive: [
    { name: 'Hubib App', kind: 'Web app', year: '2025' },
    { name: 'TCR Mobile', kind: 'iOS / Android', year: '2025' },
    { name: 'Hubib Academy', kind: 'Plataforma', year: '2026' },
    { name: 'TCR White-label', kind: 'SaaS', year: '2025' },
    { name: 'Sky Markets', kind: 'Mercado de previsão', year: '2026' },
    { name: 'Hubib Admin', kind: 'Back-office', year: '2025' },
  ],
  services: {
    label: 'Serviços',
    title: 'O que eu',
    titleB: 'entrego',
    intro: 'Cinco frentes, um mesmo cuidado. Posso entrar no começo da ideia, no meio do código ou no último detalhe de movimento.',
    deliverables: 'Entregáveis',
    items: [
      {
        title: 'Product Design',
        text: 'Do problema nebuloso ao fluxo claro. Pesquisa, jornadas, wireframes e protótipos que reduzem o risco antes da primeira linha de código.',
        deliverables: ['Pesquisa e jornadas', 'Wireframes e fluxos', 'Protótipos navegáveis', 'Testes de usabilidade'],
      },
      {
        title: 'UI & Design Systems',
        text: 'Linguagens visuais que escalam: tokens, componentes e documentação no Figma que mapeiam um para um com o código.',
        deliverables: ['Interfaces de alta fidelidade', 'Design tokens', 'Bibliotecas de componentes', 'Ilustração no Illustrator'],
      },
      {
        title: 'Front-end Engineering',
        text: 'React e TypeScript de produção: dashboards densos em dados, i18n, acessibilidade e um orçamento de performance levado a sério.',
        deliverables: ['React · TypeScript · Vite', 'Tailwind · shadcn/ui', 'i18n e acessibilidade', 'Performance'],
      },
      {
        title: 'Motion & Creative Dev',
        text: 'A camada que as pessoas lembram. Coreografia com GSAP, cenas em Three.js e shaders, sempre a serviço da história.',
        deliverables: ['GSAP · ScrollTrigger', 'Three.js · WebGL · GLSL', 'Landing pages imersivas', 'Microinterações'],
      },
      {
        title: 'Apps & Back-end',
        text: 'O mesmo cuidado fora do navegador: apps iOS e Android com React Native e Expo, e Node.js para APIs e integrações.',
        deliverables: ['React Native', 'Expo', 'Node.js', 'Integrações e APIs'],
      },
    ],
  },
  toolbox: {
    label: 'Ferramentas',
    title: 'Caixa de ferramentas',
    hint: 'Role e eu digito para você.',
    space: 'espaço para o seu projeto',
    groups: [
      { title: 'Design', items: ['Figma', 'Illustrator', 'Design Systems', 'Protótipos', 'UX Research', 'Acessibilidade'] },
      { title: 'Front-end', items: ['React', 'TypeScript', 'Vite', 'Tailwind', 'shadcn/ui', 'TanStack', 'Zod', 'i18next'] },
      { title: 'Motion & 3D', items: ['GSAP', 'Three.js', 'R3F', 'GLSL', 'Lenis', 'Framer Motion'] },
      { title: 'Mobile & back-end', items: ['React Native', 'Expo', 'Node.js', 'Git', 'Java', 'Python'] },
    ],

  },
  changelog: {
    label: 'Trajetória',
    title: 'Notas de versão',
    version: 'Daniel 31.0',
    intro: 'Minha trajetória documentada do jeito que eu documento software: por versões.',
    head: 'Você está aqui',
    kinds: { added: 'Adicionado', improved: 'Melhorado', fixed: 'Corrigido', merged: 'Merge' },
    entries: [
      {
        version: 'v19.0',
        date: '2019',
        branch: 'unopar',
        kind: 'branch',
        title: 'Análise e Desenvolvimento de Sistemas',
        place: 'Unopar · Assis (SP)',
        notes: [
          { kind: 'added', text: 'Lógica, banco de dados e engenharia de software' },
          { kind: 'added', text: 'Curso completo de Java' },
          { kind: 'added', text: '190h de UX/UI, HTML, CSS, JavaScript e React (Origamid)' },
        ],
      },
      {
        version: 'v21.0',
        date: '2021',
        branch: 'unopar',
        kind: 'merge',
        title: 'Formado',
        place: 'Merge de unopar na main',
        notes: [
          { kind: 'merged', text: 'Graduação concluída' },
          { kind: 'improved', text: 'Base sólida para unir design e código' },
        ],
      },
      {
        version: 'v24.0',
        date: '2024',
        branch: 'grupo-nexus',
        kind: 'branch',
        title: 'UI/UX Designer & Front-end Engineer',
        place: 'Grupo Nexus · desde 2024',
        notes: [
          { kind: 'added', text: 'Suíte de produtos financeiros e cripto: TCR, VCX, Hubib e Sky Markets' },
          { kind: 'improved', text: 'Web apps, landing pages, painéis e apps em React Native' },
        ],
      },
      {
        version: 'v24.1',
        date: '2024',
        branch: 'tcr-finance',
        kind: 'branch',
        title: 'Product Designer & Front-end Engineer',
        place: 'TCR Finance · desde 2024',
        notes: [
          { kind: 'added', text: 'Plataforma, mesa OTC, white-label e app iOS/Android' },
          { kind: 'added', text: 'Hero com lobo de partículas em WebGL' },
        ],
      },
      {
        version: 'v25.0',
        date: '2025',
        branch: 'hubib',
        kind: 'branch',
        title: 'Product Designer & Creative Front-end',
        place: 'Hubib · desde 2025',
        notes: [
          { kind: 'added', text: 'Maior contribuidor do app principal' },
          { kind: 'added', text: 'Landing cinematográfica com WebGL, GSAP e Lenis' },
        ],
      },
      {
        version: 'v31.0',
        date: '2026',
        branch: 'main',
        kind: 'head',
        title: 'Daniel 31.0',
        place: 'Release atual · estável',
        notes: [
          { kind: 'added', text: 'Este portfólio, do primeiro rabisco ao último easing' },
          { kind: 'improved', text: 'Design systems que vão do Figma ao código sem perda' },
          { kind: 'fixed', text: 'Nenhum padding de 15px sobreviveu' },
        ],
      },
    ],
    languagesTitle: 'Idiomas',
    languages: 'Português (nativo) · Inglês',
    educationTitle: 'Formação',
    education: [
      { title: 'Análise e Desenvolvimento de Sistemas', place: 'Unopar, Assis (SP)', detail: '2019 a 2021' },
      { title: 'UX/UI Design · HTML & CSS · JavaScript · React', place: 'Origamid', detail: '190h de cursos intensivos' },
      { title: 'Java completo', place: 'Unopar', detail: 'Curso completo' },
      { title: 'Python', place: 'Udemy', detail: 'Fundamentos de back-end' },
    ],
  },
  contact: {
    label: 'Contato',
    titleA: 'Tem um',
    scribble: 'rabisco',
    titleB: 'por aí?',
    text: 'Eu transformo em produto. Aberto a vagas full-time e projetos freelance selecionados, remoto para qualquer lugar do mundo.',
    copy: 'Copiar e-mail',
    copied: 'Copiado para a área de transferência',
    whatsapp: 'Chamar no WhatsApp',
    response: 'Respondo em até 24h',
    socials: 'Redes',
    more: 'Continue rolando. Tem mais uma coisa.',
  },
  finale: {
    joined: 'Daniel entrou no arquivo',
    file: 'Portfólio · Daniel Liberto',
    pages: ['Site', 'Design system', 'Rabiscos'],
    layers: 'Camadas',
    design: 'Design',
    prototype: 'Protótipo',
    you: 'Você',
    comment: 'Tudo o que você acabou de ver foi desenhado aqui e construído lá. Gostou? Vamos fazer o seu.',
    reply: 'Responder por e-mail',
    present: 'Apresentar',
    hint: 'Arraste para navegar · Ctrl + scroll para zoom',
    hintTouch: 'Arraste para navegar · pinça para zoom',
    zoomIn: 'Aproximar',
    zoomOut: 'Afastar',
    fit: 'Ver tudo',
    frames: [
      { id: 'hero', name: 'Hero' },
      { id: 'manifesto', name: 'Manifesto' },
      { id: 'process', name: 'Processo' },
      { id: 'work', name: 'Projetos' },
      { id: 'services', name: 'Serviços' },
      { id: 'toolbox', name: 'Ferramentas' },
      { id: 'changelog', name: 'Notas de versão' },
      { id: 'contact', name: 'Contato' },
    ],
    tokensTitle: 'Cores',
    typeTitle: 'Tipografia',
    componentsTitle: 'Componentes',
    credits: 'Créditos',
    creditsText: 'Desenhado no Figma e construído com React, TypeScript, Three.js, GSAP, Lenis e Matter.js.',
    sticky: 'lembrar: contratar o Daniel',
  },
  postCredits: {
    label: 'Cena pós-créditos',
    credits: [
      { role: 'Direção', name: 'Eu' },
      { role: 'Roteiro', name: 'Também eu' },
      { role: 'Product Design', name: 'Eu de novo' },
      { role: 'Interface', name: 'Adivinha? Eu' },
      { role: 'Front-end', name: 'Ainda eu' },
      { role: 'Motion & WebGL', name: 'Sim, eu (de novo)' },
      { role: 'Efeitos visuais', name: 'Three.js · GSAP' },
      { role: 'Scroll suave', name: 'Lenis' },
      { role: 'Trilha sonora', name: 'Tone.js (gerada por código)' },
      { role: 'Revisão de pixels', name: 'Os óculos do Daniel' },
      { role: 'Catering', name: 'Café. Muito café.' },
      { role: 'Agradecimentos especiais', name: 'Você, por ter descido até aqui' },
    ],
    creditsTitle: 'Créditos',
    disclaimer: 'Nenhum pixel foi ferido durante a produção deste site.',
    presents: 'apresenta',
    presentsTitle: 'Pós-créditos',
    thanks: 'Obrigado por ter assistido até o fim, inclusive os créditos. Se o portfólio te fez sorrir, imagina o seu produto. Me chama para conversar.',
    end: 'Agora sim, fim.',
    top: 'Voltar ao topo',
  },
  footer: {
    built: 'Desenhado e desenvolvido por Daniel Liberto.',
    rights: 'Todos os direitos reservados.',
    top: 'Voltar ao topo',
    local: 'Horário local',
  },
  notFound: {
    title: 'Frame não encontrado',
    text: 'Esta página foi apagada do arquivo, ou nunca existiu.',
    cta: 'Voltar ao início',
  },
}
